version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - airflow_network

  airflow-webserver:
    image: airflow:latest  # Use 'airf225' if you have a custom image
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.basic_auth"
      AIRFLOW_WWW_USER_USERNAME: userairf
      AIRFLOW_WWW_USER_PASSWORD: password
    volumes:
      - ./airflow:/opt/airflow
    networks:
      - airflow_network
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: airflow:latest
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./airflow:/opt/airflow
    networks:
      - airflow_network
    command: scheduler

  hue:
    image: gethue/hue:latest
    environment:
      HUE_DATABASE_ENGINE: postgresql_psycopg2
      HUE_DATABASE_NAME: airflow
      HUE_DATABASE_USER: airflow
      HUE_DATABASE_PASSWORD: airflow
      HUE_DATABASE_HOST: postgres
      HUE_DATABASE_PORT: 5432
    depends_on:
      - postgres
    networks:
      - airflow_network
    ports:
      - "8888:8888"

volumes:
  postgres_data:

networks:
  airflow_network:
    driver: bridge
